# Generated by Django 3.0.2 on 2020-09-17 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=250)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fullName', models.CharField(default='', max_length=250)),
                ('email', models.CharField(default='', max_length=250)),
                ('phone', models.CharField(default='', max_length=250)),
                ('username', models.CharField(default='', max_length=250)),
                ('password', models.CharField(default='', max_length=250)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField()),
                ('address', models.CharField(default='', max_length=250)),
                ('latitude', models.CharField(default='', max_length=250)),
                ('longitude', models.CharField(default='', max_length=250)),
                ('product_Id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Product')),
                ('user_Id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.UserInfo')),
            ],
        ),
    ]
