# Generated by Django 3.0.2 on 2020-09-17 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_userinfo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 12, 36, 29, 801315, tzinfo=utc), verbose_name='date'),
        ),
    ]
