# Generated by Django 3.0.2 on 2020-09-17 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 13, 8, 59, 104664, tzinfo=utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(default='', max_length=250),
        ),
    ]
